version: "3.9"
services:      
  school:
    container_name: school
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.address" : "0.0.0.0",
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/school?allowPublicKeyRetrieval=true&useSSL=false"
      }'
        
  mysqldb:
    image: mysql:8.0.28
    container_name: mysql
    environment:
      MYSQL_DATABASE: "mysql"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
